name: Build and Deploy Website

on:
  workflow_run:
    workflows: ["Build LaTeX documents"]
    types:
      - completed

  # 🔥 Aggiungi questo blocco:
  push:
    paths:
      - 'site/**'  # Qualsiasi file modificato all’interno di site/

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Esegui solo se il workflow precedente ha avuto successo
    # oppure se è un push nella cartella site/
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run build_site.py
        run: python build_site.py
        working-directory: ./site

      - name: Prepare artifact
        run: |
          mkdir -p site/docs
          cp -r docs/* site/docs/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
